[tasks.install-llvm-tools]
install_crate = { rustup_component_name = "llvm-tools" }

[tasks.flip-link]
install_crate = { crate_name = "flip-link", binary = "flip-link", test_arg = ["-h"] }



[tasks.build]
command = "cargo"
args = ["build", "--release"]
#dependencies = ["clean"]

[tasks.objcopy]
install_crate = { crate_name = "cargo-binutils", binary = "cargo", test_arg = [
    "objcopy",
    "--help",
] }
command = "cargo"
#args = ["objcopy", "--release", "--", "-O", "ihex", "rmk.hex"]
args = ["objcopy", "--release", "--", "-O", "binary", "out.bin"]
dependencies = ["install-llvm-tools", "flip-link", "build"]
